### ISSUE TITLE
Missing string strategy

### ISSUE THREAD

**Issue by nvie** [DRMacIver/hypothesis#101]
I was giving this library a spin, and the first example I tried was this:

```python
@given(text())
def test_me(s):
    assert s.strip() == s.lstrip()
```

And it passed. If I change `s.lstrip()` to `s.rstrip()`, it correctly fails with a falsifying example of `' 0'`, which is what I indeed expected.

If `'0 '` was also tried, it would have caught the bug in the `.lstrip()` version, too.

**Comment by DRMacIver** [comment]
I think it's a coincidence that one passed and the other did not. If you rerun it it would probably also fail.

It sounds like hypothesis isn't generating whitespace characters with a high enough probability though. That's pretty plausible and I agree it should be fixed.

**Comment by nvie** [comment]
Oh wow. I ran both at least 5 times, and it kept structurally passing for the `.lstrip()` case, and structurally failing for the `.rstrip()` case. Now that I ran it more often, it indeed fails as expected. Guess I got beaten by the odds! Awesome library, though :) And thanks for the quick response!

**Comment by DRMacIver** [comment]
Yeah, it's one of the unfortunate downsides of randomized testing that some bugs are hit with too low a probability to reproduce reliably and this can fool you. It's a large part of what the Hypothesis database is for - once it's found a bug it doesn't forget about it so you're not fooled into thinking it's fixed.

It does sound like there's a bug here about not producing whitespace characters with high enough probability though. I'll file a separate issue to fix this.
