### ISSUE TITLE
For tests failing on explicitly supplied examples, hypothesis does not print falsifying inputs

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [DRMacIver/hypothesis#103]
```python
import hypothesis


@hypothesis.given(hypothesis.strategies.integers())
@hypothesis.example(2)
def example_test(x):
    assert x != 2


example_test()
```

Expected:
```
Falsifying example: example_test(x=2)
Traceback (most recent call last):
  ...
AssertionError
```

Got:
```
Traceback (most recent call last):
  ...
AssertionError
```

(hypothesis 1.8.2)

**Comment by DRMacIver** [comment]
Hmm. That's a good point. I think when I wrote that I hadn't figured out how to do it correctly (there are some complications in terms of the order in which you do things. The behaviour of the explicit examples is actually completely distinct from the main body of given), but I think I can make this work correctly now. Should have something for you shortly.

**Comment by DRMacIver** [comment]
If you update to 1.8.3 this should be fixed.
