### ISSUE TITLE
`just(value)` uses non-unicode string for repr

### ISSUE THREAD

**Issue by subsetpark** [DRMacIver/hypothesis#108]
When attempting to display falsifying example, it triggers a traceback:

```
  File "/Users/zachsmith/envs/mksp-site/lib/python2.7/site-packages/hypothesis/searchstrategy/flatmapped.py", line 49, in pack
    return morpher.become(strategy(self.expand(source)))
  File "/Users/zachsmith/mksp/site/mksp/tests/hypothesis/strategies.py", line 81, in with_some_requests
    container_cycle=stored_cycles(booking.user),
  File "/Users/zachsmith/mksp/site/mksp/tests/hypothesis/strategies.py", line 46, in stored_cycles
    user=just(user))
  File "/Users/zachsmith/envs/mksp-site/lib/python2.7/site-packages/hypothesis/strategies.py", line 83, in just
    JustStrategy(value), 'just(%r)' % (value,))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 11: ordinal not in range(128)
```

**Comment by DRMacIver** [comment]
So it does. I'll add the workaround in there too. But I must again point out that your repr implementation is wrong and you should fix it.

**Comment by DRMacIver** [comment]
In all honesty I'm increasingly unconvinced working around broken repr implementations is a good idea.

**Comment by subsetpark** [comment]
I think I lack some context... Mine, personally? Or Django's? If it's mine, I'd be very eager to fix it, I just can't tell from the traceback what the offending method is.

**Comment by DRMacIver** [comment]
Oh! Sorry. I was confused and was thinking you were the one who reported the last one of these but it was someone else.

The problem here is that it's illegitimate to have a non ASCII repr in python 2.7. If you're using just with a value that tries to do that then you'll get an error.

I'd guess the culprit is you have a model which tries to include a text field directly in its repr

**Comment by subsetpark** [comment]
Is it possible to have hypothesis report on that as well?

**Comment by DRMacIver** [comment]
It's possible but is a bit fiddly. Hypothesis needs a functioning repr to report values. I have some workarounds and I should definitely do some work on making this easier to understand but it's a somewhat never ending problem.

**Comment by DRMacIver** [comment]
At any rate, looks like this should be possible to handle relatively transparently. I'll be doing a release in the next hour or two that might fix your problem.

**Comment by DRMacIver** [comment]
ok. That time frame was optimistic. Probably tomorrow or otherwise soon though.

**Comment by DRMacIver** [comment]
This did end up shipping and I forgot to close the bug. Sorry. This should all work transparently now.
