### ISSUE TITLE
Provide mechanism for (progress) feedback

### ISSUE THREAD

**Issue by ulope** [DRMacIver/hypothesis#11]
Great library! Thanks for making it :)

It would be great if there would be a way to get progress feedback.
As a start I think it would be a good idea to use Python's logging system to provide some basic stats like number of tested permutations, time taken and so on. Additionally some kind of progress callback could be very useful.

**Comment by DRMacIver** [comment]
The new verbose output feature in 1.3 should satisfy this requirement
