### ISSUE TITLE
hypothesis will break if database is disabled

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [DRMacIver/hypothesis#111]
```python
import hypothesis
from hypothesis import strategies

@hypothesis.given(strategies.integers())
def test(x):
    pass

hypothesis.Settings.default.database_file = None
test()
```

```
Traceback (most recent call last):
  ...
  File ".../hypothesis/core.py", line 502, in wrapped_test
    storage = settings.database.storage(
AttributeError: 'UniqueIdentifier' object has no attribute 'storage'
```

hypothesis 1.8.2

**Comment by DRMacIver** [comment]
Hmm. That's definitely not ideal. Will fix.

Fwiw you can achieve the desired effect with

Settings.default = Settings (database=None)

**Comment by DRMacIver** [comment]
By the way, can you elaborate on why you want to disable the database?

**Comment by Vlad-Shcherbina** [comment]
I think reproducible runs are important for continuous testing (or what do you call it). It would be annoying if somebody else got their breaking change into master branch past the buildbot or precommit hooks purely by luck, and I ran into it while working on completely unrelated feature.

For such development processes, probably there should be two modes to run randomized tests: "adventurous" (invoked manually, new seed every time, with example db, perhaps with higher max_examples limit), and reproducible (employed in automated test runs).

Sure, this is just an approximation, as there always will be some subtle sources of nondeterminism, but it does not mean that the most blatant ones should not be eliminated.

By the way, am I correct that the following snippet gets rid of all hypothesis-specific nondeterminism?
```python
hypothesis.Settings.default.timeout = -1
hypothesis.Settings.default.database_file = None
hypothesis.Settings.default.derandomize = True
```

**Comment by DRMacIver** [comment]
That should be is, yet, though there are enough uses of floating point internally that it's deterministic but not necessarily reproducible across systems

**Comment by DRMacIver** [comment]
This should now be fixed (actually fixed a few weeks ago but I forgot to close the bug)
