### ISSUE TITLE
Allow varargs when using only keyword arguments

### ISSUE THREAD

**Issue by jerith** [DRMacIver/hypothesis#113]
If a test function is wrapped by another decorator, it may be hard to avoid varargs. However, it should still be safe to use `@given` if no positional arguments are used.

I have experimented with this by modifying `run_test_with_generator` to do the following instead of the current vararg check:
```python
        if generator_arguments and original_argspec.varargs:
            raise InvalidArgument(
                'varargs are not supported with positional arguments to @given'
            )
```

`tox -e py26,py27` passes locally for me, so I have reasonable confidence that this doesn't break anything obvious. If you're okay with this change, I'm happy to submit a pull request with the necessary tests and such.

**Comment by DRMacIver** [comment]
Yes, this seems like a reasonable change.

**Comment by Vlad-Shcherbina** [comment]
I think it still behaves in a weird way if decorated test `@given` produces (not `@given` itself) is passed positional arguments. This case is important when decorated test is invoked as instance method and receives `self` positional argument.

Consider the following snippet:
```python
import hypothesis

class C(object):
    @hypothesis.given(x=hypothesis.strategies.integers())
    def t(*args, **kwargs):
        print(args, kwargs)

C().t()
```

I would expect it to produce something like
```
(<__main__.C object at 0xfffff>,) {'x': 0}
(<__main__.C object at 0xfffff>,) {'x': 42}
...
```
but instead I got just
```
() {'x': <__main__.C object at 0xfffff>}
```

hypothesis-1.10.1

**Comment by jerith** [comment]
I've just noticed this myself. I forgot to test that case. :-(
