### ISSUE TITLE
Hypothesis does not find good failing example for strategy involving flatmap

### ISSUE THREAD

**Issue by inglesp** [DRMacIver/hypothesis#127]
The following strategy does not produce anything approaching a minimal failing example:

````
>>> strategy = integers(min_value=0, max_value=10).flatmap(lambda w: lists(lists(sampled_from('ab'), min_size=w, max_size=w)))
>>> example = find(strategy, lambda x: ['a', 'b'] in x)
>>> len(example)
28
````

See https://gist.github.com/inglesp/70f30977b4b25182cbb9 and discussion on IRC for some background.

**Comment by DRMacIver** [comment]
1.10.2 is out, which contains a fix for this bug. It turned out to be to do with how Hypothesis tracks duplicate examples.
