### ISSUE TITLE
Integrate Django models generation with Factory Boy

### ISSUE THREAD

**Issue by thedrow** [DRMacIver/hypothesis#130]
Factory Boy already allows you to provide definitions for models with fuzzy examples.
It will also provide us with a way to create new examples which are not saved in the database.

**Comment by DRMacIver** [comment]
So [I looked into this a while ago and I wasn't really convinced there was anything to do here](http://www.drmaciver.com/2015/06/using-hypothesis-with-factory-boy/). Do you have a specific thing in mind that is currently hard to do?

**Comment by thedrow** [comment]
A cleaner syntax would work better.
Something like:
```python
models(UserFactory, strategy=factory.BUILD_STRATEGY)
```
or
```python
models(using=UserFactory.build)
```
Both of them will allow provide keyword arguments to the build/create method.
You could go with creating a registry for factories and using the model's class to match with that factory as well.

**Comment by DRMacIver** [comment]
I'm still really unconvinced to be honest. The syntax is not particularly different, and you're suggesting a lot of complexity for really very little benefit.

**Comment by thedrow** [comment]
It's easier to use and to learn. That's about it.
Feel free to close this issue if you feel different.

**Comment by DRMacIver** [comment]
builds() is really not a hard thing to learn, and it gives you almost the most direct possible way of using things you're used to from fakefactory.

If you want to submit a pull request for this I'd be happy to take a look, but there's basically zero chance of my ever implementing it, sorry.
