### ISSUE TITLE
hypothesis-pytest: __multicall__ is deprecated

### ISSUE THREAD

**Issue by The-Compiler** [DRMacIver/hypothesis#137]
When using the pytest master from github with hypothesis-pytest, I get this pytest warning:

```
.../hypothesispytest/__init__.py:41 'pytest_runtest_makereport' hook uses deprecated __multicall__ argument
```

I think the preferred way to do this kind of thing is to use `@pytest.mark.hookwrapper`, similar to what you did with `pytest_pyfunc_call`.

**Comment by DRMacIver** [comment]
Now fixed in master.
