### ISSUE TITLE
non-negative numbers? numbers in a range? one of? constant?

### ISSUE THREAD

**Issue by willf** [DRMacIver/hypothesis#14]
Could you tell me how, using the @given syntax, one goes about:

- specifying a non-negative int or float? positive? negative? non-positive?
- specifying an int or float in a range?
- using one_of?
- specifying a constant (Just) value? 

e.g.
```python
@given(nonneg)
def test_something(x):
  assert something(x) == True
```

**Comment by DRMacIver** [comment]
A lot of this is currently not easy to do I'm afraid. I'd like to fix that, and have some plans to do so.

For just and one\_of I've now added some tests to test_testdecorators to demonstrate how they work: https://github.com/DRMacIver/hypothesis/blob/master/hypothesis/tests/test_testdecorators.py#L144

For the others you would currently have to write your own strategy, which is a bit involved. You could also use the assume syntax to impose it as a precondition. e.g. 

    @given(int)
    def test_something(x):
        assume(x >= 0)
        assert something(x) == True

This should work fine for the case of non-negative numbers, but you will probably have too high a rejection rate for small intervals.

**Comment by willf** [comment]
Thank you, David.

**Comment by DRMacIver** [comment]
FWIW, there is now support for integer and floats in bounded ranges. 


    In [1]: from hypothesis.descriptors import integers_in_range, floats_in_range

    In [2]: from hypothesis.testdecorators import given

    In [3]: @given(integers_in_range(1, 10))
       ...: def test_a_thing(x):
       ...:     print(x)
       ...:     

    In [4]: test_a_thing()
    6
    4
    8
    10
    9
    2
    3
    5
    7
    1

floats_in_range will work identically.
