### ISSUE TITLE
Not possible to pip install Hypothesis under python 3.2

### ISSUE THREAD

**Issue by tobgu** [DRMacIver/hypothesis#141]
Just wanted to let you know that it is not possible to install hypothesis under python 3.2.

```
Collecting hypothesis
  Using cached hypothesis-1.11.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-jwg90_/hypothesis/setup.py", line 36, in <module>
        exec(o.read())
      File "<string>", line 20
        __version__ = u'.'.join(map(str, __version_info__))
                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jwg90_/hypothesis
```

Don't know if the same type of problems exists in other parts of the code. I'm not really depending on python 3.2 support but if it's an easy fix it may be worthwhile to continue supporting it. Otherwise the README should probably be updated to reflect that 3.2 is no longer supported.

Thanks!

**Comment by DRMacIver** [comment]
Oops. Yes. Apparently at some point I silently dropped 3.2 support and forgot to update the docs. Sorry about that!

This is unlikely to change - 3.0 through 3.2 are more or less unusably broken, particularly if I also want to support 2.7. I'll close this issue once I've updated the docs.

**Comment by DRMacIver** [comment]
Documentation now updated.
