### ISSUE TITLE
Invalid list comprehension

### ISSUE THREAD

**Issue by kkurzhal** [DRMacIver/hypothesis#147]
On line 92 in /hypothesis/extra/django/models.py, the list comprehension is invalid:
`missed = {x for x in mandatory if x not in extra}` --> `missed = [x for x in mandatory if x not in extra]`

**Comment by DRMacIver** [comment]
No it's not. It's a set comprehension.

**Comment by kkurzhal** [comment]
Ah, interesting!  I didn't realize that this was a feature in Python 2.7+.  I ran into this problem because Python 2.6 is being used, which does support the set comprehension notation.

**Comment by DRMacIver** [comment]
In general Python 2.6 is supported, but in this particular instance there aren't any supported versions of Django which also support Python 2.6, so it doesn't matter. If you're trying to use the Django support on Python 2.6 it's very unlikely to work.
