### ISSUE TITLE
floats() with min_value = 0.0 gives poor distribution of floats

### ISSUE THREAD

**Issue by dhait** [DRMacIver/hypothesis#148]
When floats(min_value=0.0) is used, all generated floats are between 0.0 and 1.0 (except for inf)
When floats() is used, the generated floats cover the whole range of valid floating-point numbers.

**Comment by DRMacIver** [comment]
Huh. That's unfortunate.

It's not entirely right (you do sometimes get larger floats), but the distribution is definitely very sharply peaked in the [0, 1] range and almost never goes much above that. I'll fix it. Thanks for the catch.
