### ISSUE TITLE
Ship documentation and tests in tarball

### ISSUE THREAD

**Issue by vincentbernat** [DRMacIver/hypothesis#149]
Hi!

I am packaging hypothesis in Debian. It would be helpful to have documentation and tests shipped in tarball too to propose a package with documentation and to run unittests on build. Shipping `CONTRIBUTOR.rst` would also be nice.

I can do a PR if needed.

**Comment by DRMacIver** [comment]
Do the github tarballs for version tags not do what you want?

**Comment by vincentbernat** [comment]
Yes, they do. Let's use them.
