### ISSUE TITLE
Allow override Settings.database property via setattr

### ISSUE THREAD

**Issue by kxepal** [DRMacIver/hypothesis#152]
I would be nice to have a legal way to globally change default example database and only. The most intuitive way seems to be:

```
import hypothesis
import hypothesis.database

hypothesis.Settings.default.database = hypothesis.database.SQLiteBackend()
```

Gives:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    hypothesis.Settings.default.database = hypothesis.database.SQLiteBackend()
  File "/usr/local/opt/virtualenv/aiocouchdb/lib/python3.3/site-packages/hypothesis/settings.py", line 210, in __setattr__
    raise AttributeError(u'No such setting %s' % (name,))
AttributeError: No such setting database
```

Currently, it's possible only through private property:

```
hypothesis.Settings.default._database = hypothesis.database.SQLiteBackend()
```

Or by overriding all default settings with new instance:
```
hypothesis.Settings.default = Settings(database=hypothesis.database.SQLiteBackend())
```

What may accidentally erase some other changes to default settings made somewhere else.

**Comment by DRMacIver** [comment]
This is definitely a bug, but note that Settings.default = Settings(database=blah) actually *does* do exactly what you want. A newly created Settings object inherits its default values from the current default Settings, so this only changes the one value.

The Hypothesis Settings system is a bit magical and very under documented. Sorry about that.

**Comment by kxepal** [comment]
Nice magic! Good to know. Then one worry less (:

**Comment by DRMacIver** [comment]
This is now fixed in master.
