### ISSUE TITLE
Tests using strategies with invalid arguments should error at execution time, not definition

### ISSUE THREAD

**Issue by DRMacIver** [DRMacIver/hypothesis#176]
See discussion on #22 for details.

The problem in this case is that @mulkieran wants to be able to skip tests in cases where they have an invalid strategy involved (e.g. because of an empty sampled from), but in general it seems a bit rude for a user error to stop executing tests entirely.

The solution is to raise the InvalidArgument error at test execution time instead of definition.

I propose the following solution:

1. Create an 'InvalidStrategy' SearchStrategy subtype that can not generate examples but will raise InvalidArgument on *any* of the standard strategy methods called on it. It will do this by first calling a custom function which is expected to raise InvalidArgument and asserting false afterwards to prevent fallthrough.
2. Create a catches_invalid decorator for use in hypothesis.strategies. This executes the called function and returns its result, but if an InvalidArgument is thrown creates instead an InvalidStrategy which will re-execute the relevant function at test time.

This should mean you get exactly the same InvalidArgument exceptions, but they happen within the tests instead of at the definition time. In particular it becomes possible to skip tests that would otherwise raise InvalidArgument.

@mulkieran, can you confirm whether you think this would satisfy your use case?

**Comment by mulkieran** [comment]
Thanks, this does seem like it would answer my problem.

Would greater laziness in constructing all the strategies also do the trick? I have almost no understanding of the architecture of hypothesis or pytest for that matter, so there may be obvious reasons why that wouldn't be any help at all.

**Comment by DRMacIver** [comment]
I think this is more or less already a greater laziness solution, but it has the advantage of not inserting indirection in places you don't need it.

**Comment by DRMacIver** [comment]
Fixed in 1.16.0

**Comment by mulkieran** [comment]
Thanks!
