### ISSUE TITLE
UUID strategy

### ISSUE THREAD

**Issue by jml** [DRMacIver/hypothesis#207]
In many places in ClusterHQ/eliot and ClusterHQ/flocker, we'd like to have an arbitrary UUID.
It'd be nice if Hypothesis came with a UUID strategy out of the box.

We currently use something like this to do the generation:

```python
uuids = basic(generate=lambda r, _: unicode(UUID(int=r.getrandbits(128))))
```

**Comment by DRMacIver** [comment]
I agree this would be useful.

One thing I was wondering: Given that you actually want your UUIDs to be unique each time, I wonder if builds(uuid4) would be a better fit for what you want?

**Comment by jml** [comment]
Almost certainly! Will give it a shot.

**Comment by DRMacIver** [comment]
In 1.14.0 (just released) there is now a uuids() strategy.
