### ISSUE TITLE
Server (edit: previously "Library") mode for Hypothesis

### ISSUE THREAD

**Issue by daltonwoodard** [DRMacIver/hypothesis#210]
The core functionality of Hypothesis is wonderful, but it would be nice to be able to use Hypothesis in a "library mode", let us call it libhyp for the moment. By this I mean, instead of writing (as in the documentation):

```python
from hypothesis import given
from hypothesis.strategies import text

@given(text())
@example(s='')
def test_decode_inverts_encode(s):
    assert decode(encode(s)) == s
```

one could indirectly use hypothesis as a backend for data generation and case simplification, roughly in the form:

```python
from libhyp import State, strategies

def decode_inverts_encode(s):
    return decode(encode(s)) == s

def test_decode_inverts_encode(state):
    while state.run():
        s = state.draw()
        if not decode_inverts_encode(s):
            state.failed(s)

def main():
    state = State(strategy=strategies.text(), max_examples=500)
    test_decode_encode(state)
    # do something interesting with the results

if __name__ == 'main':
    main()
```

My desire is to eventually use something analogous to the above as a master program interfacing with unit tests written in other languages (sub-processed out), conveying test cases generated by Hypothesis and results back to Hypothesis for case simplification.

After poking around in the source files and observing the current architecture, it seems this functionality shouldn't be *too* hard to implement.

Has anyone attempted an implementation of this in the past? If so, where may they be found?

**Comment by DRMacIver** [comment]
I don't think I understand what you're trying to achieve. Could you explain what the problem you're trying to solve is?

In particular, how is this different from just writing normal unit tests for code written in other languages from within Python?

**Comment by DRMacIver** [comment]
Note in particular the decorator isn't part of any sort of test runner. It just exposes a function you can call. The test\_blah notation is to let py.test pick it up. Hypothesis is pretty aggressively just a library, with given and find being the main entry points to its data generation, which is why I'm a bit confused by the question.

**Comment by daltonwoodard** [comment]
(perhaps, if nothing else, I could attempt an implementation of the State mechanism above)

Yes, of course; let me elaborate. Let's say I have written a numerical linear algebra system in some other language, say C, and that I am interested in doing property based testing of the implementation.

As a simple example maybe I wish to test that matrix transposition is an involution.

```c
#include "some_numerical_library.h"

matrix_t * transpose (matrix_t * a)
{
    // for brevity's sake I'll omit the actual code
    return a;
}
```

An implementation of the test might look like:

```
#include "some_numerical_library.h"
#include "transpose.h"

bool transpose_is_involution (matrix_t * a)
{
    matrix_t * b = matrix_copy (a);
    bool result = matrix_eq (b, transpose (transpose (a)));
    matrix_delete (b);
    return result; 
}

int main (void)
{
    // init some interface with the master Python program
    /// (or maybe the data is just read from the spoof'd stdin
    unit_test_state state; // some C implementation for interfacing with Python
    // initialize
    // ...
    while (state.run()) {
        matrix_t * a = state.draw();
        state.result (transpose_is_involution (a));
        // cleanup `a`
    }
}
```

What I want to achieve is passing data back and forth from this program above to a master program written in Python which back-ends Hypothesis to create the matrices, simplify failing cases, et cetera.

Indeed, I could just use some unit testing framework written for C, *but* such frameworks typically cannot achieve anything like what Hypothesis can do.

**Comment by daltonwoodard** [comment]
If what I'm trying to do is already trivial somehow with the existing project please let me know. It is just that from what I've been able to gather so far, Hypothesis seems to be localized to the Python community.

**Comment by DRMacIver** [comment]
Well, the eventual solution to this is [Conjecture](http://github.com/DRMacIver/conjecture).

In the meantime I think you're going to find it much easier to test C code from Python using [CFFI](https://cffi.readthedocs.org/en/latest/) rather than trying to wrap Hypothesis into a usable C API. The API you're describing wouldn't be very hard to implement on top of the Hypothesis internal API, but I suspect that it's the easy part of what you want here.

**Comment by DRMacIver** [comment]
An alternative meantime is [theft](https://github.com/silentbicycle/theft), which doesn't implement the generators for you but is otherwise rather good.

**Comment by daltonwoodard** [comment]
Oh, to be clear I'm not actually testing C code. That was just an example of what might be possible.

I have looked at Conjecture a bit; what are your plans for that project? Is it meant to be a library to interface with or a port of Hypothesis to C? And theft does look interesting; thank you for the link.

**Comment by daltonwoodard** [comment]
I think I shall fork the project and see what can be done about prototyping some "state" mechanism; it will be useful for some projects I am currently working on.

As a side note, what I am currently implementing is an automated unit testing framework (read: framework, not case generation or simplification). I have a prototype in the works for C++11/14, but the goal is to make it language agnostic (so it may involve very basic code generation; we shall see). My desire is to be able to use Hypothesis and/or other Quickcheck style libraries as backends for dynamic randomized case generation.

**Comment by daltonwoodard** [comment]
I have changed the title, because I now realize what I am asking about is really a client/server model of usage for Hypothesis.

**Comment by DRMacIver** [comment]
Conjecture is meant to be a library that you can interface with or use directly from C to do something similar to what Hypothesis does in any language. It will probably become an optional future backend for Hypothesis.

My inclination is that a server mode for Hypothesis is going to end up being strictly worse than using Conjecture or writing tests from Python. You're going to run into a lot of the same issues that resulted in Conjecture having a radically different API from Hypothesis, and you're not going to be able to use a lot of the tools for strategy composition that work well from within Python.

If you still want to have a go at working on it, I'm very happy to help you out and offer you advice, but this is probably going to be a lot of work and I think you're better off prototyping something you're happy with on top of Hypothesis rather than trying to get it into Hypothesis itself. Once you've got that we can talk about how to either merge it into Hypothesis itself or provide you a stable API with the points that you need to build on top of (something akin to the state object you propose).

**Comment by daltonwoodard** [comment]
I've taken a closer look at Conjecture, and I think that is what I would prefer to work on (I have a couple years of experience in C, less so in Python). For my purposes it makes sense to have an external library to interface with, regardless of the language it's implemented in.

On that note, reading through the documentation and code for Conjecture I have a few ideas (if this is not an appropriate place to be discussing Conjecture, please let me know and I'll move over there, but this should be fairly short).

First (I hope this doesn't sound absolutely insane) have you considered writing conjecture in C++, while providing entry points to the library in C by use of `extern "C"` as necessary? I believe it may greatly simplify the codebase and allow for a more expressive coding style.  For instance, rather than

```c
double x = conjecture_draw_double (context);
```

it is trivial in C++ to do something like the following (very roughly):

```c++
// define a functor for converting raw bytes to double
struct convert_double {
    static constexpr byes_needed = sizeof(double);  // to afford the context knowledge of what we're doing
    double operator() (std::array<unsigned char, bytes_needed> drawn) // provided by context
    {
        // covert the sizeof(double) bytes into whatever we need.
    }
};

// ...
// now do:
double x = conjecture::draw (context, convert_double);

// if we care about satisfying some requirement on what kind of doubles we draw,
// let us suppose conjecture::draw is polymorphic and maybe we defined a function returning
// bool to let context know that what was just drawn didn't satisfy our needs, and hence the buffer
// should be simplified. Maybe even this should be a functor that also provides heuristics to aid the
// simplification process.
double y = conjecture::draw (context, convert_double, ensure_small_double);
```

My motivation for the approach above comes from the documentation itself. The simplification process seems to be uniform on all cases: (1) smaller is better, (2) lexicographic ordering is used as a heuristic.
To me this screams generality, so why not generalize the `draw` method?

I have several ideas along these lines. Let me know what you think. If you're committed to maintaining development in C perhaps something could be arranged with a fork of the project, and I'll see what can be done about the approach outlined above.

**Comment by DRMacIver** [comment]
I'm pretty committed to it being in C. I do plan to offer a more idiomatic C++ API on top of it.

The reason not to make the draw function generic is that there's not much to genericize. A draw function is just anything that takes a test context - it can take additional arguments, or whatever. The generality comes from the underlying implementation and doesn't really need much in the way of an additional abstraction on top of that, though bindings for individual languages can certainly offer appropriate abstractions.

You're welcome to fork the project, but note that this will probably present licensing difficulties for people using your fork as Conjecture is GPL with optional commercial licenses, and I will not be able to offer those licenses to people using a fork.

**Comment by DRMacIver** [comment]
Given the conclusion is now that neither of us want this, I'm going to close this issue, but am happy to continue discussing the underlying requirements.
