### ISSUE TITLE
`strategy.choices`  should support picking from an empty list.

### ISSUE THREAD

**Issue by tomprince** [DRMacIver/hypothesis#220]
I'd assume this would behave basically like `assume(len(...)>0)'.

**Comment by radix** [comment]
This sounds like it could lead to some unintentionally weakened tests. Is there a case where you wouldn't just want to use something like `lists(..., min_size=1)`?

**Comment by tomprince** [comment]
The case I have, the list depends non-trivially on other generated data, and the case where the list is empty is a degenerate case where there is nothing to test.

**Comment by DRMacIver** [comment]
Hi,

Sorry for the delay in replying to this.

Unfortunately my reply is that I think this is really not a good idea. If you want to assume that the value is non-empty, you should do that explicitly. Implicitly doing it would be very surprising and I think is more likely to mask errors than do anything useful, while requiring you to explicitly do this is not a great deal of work and is much more explicit and clear in the actual test.

**Comment by tomprince** [comment]
How about something like `allow_empty` as a parameter to `choice` to allow it?

**Comment by DRMacIver** [comment]
What benefit would that bring over just explicitly making the assume yourself?
