### ISSUE TITLE
OneCharStringStrategy doesn't validate data from the database is permitted

### ISSUE THREAD

**Issue by DRMacIver** [DRMacIver/hypothesis#250]
It should check that the character it gets back from the database is a valid one, otherwise it can deserialize forbidden templates.

**Comment by kxepal** [comment]
Will take care about. What the behavior should be on this? Drop stored template and try clean new one?

**Comment by DRMacIver** [comment]
from_basic is supposed to raise BadData if the data is given is invalid (that's what the various check\_blah functions do). What to do about that is handled elsewhere and doesn't need any special logic.

**Comment by DRMacIver** [comment]
A thing that might also make sense is to have reify do assume(self.is_good(value)) as a total guard against mismatches here - then the template logic only has to keep the characters good on a "best effort" basis.

**Comment by kxepal** [comment]
Ok, will cook something from this. Thanks!

**Comment by DRMacIver** [comment]
This should now be fixed in 3.0
