### ISSUE TITLE
Error in composite strategy causes rain of similar tracebacks

### ISSUE THREAD

**Issue by kxepal** [DRMacIver/hypothesis#252]
Script to reproduce:
```
import unittest
from hypothesis import given
from hypothesis import strategies as st


@st.composite
def my_awesome_strategy(draw):
    1/0


class TestCase(unittest.TestCase):

    @given(my_awesome_strategy())
    def test_awesome_feature(self, arg):
        pass
```

[Example output](https://gist.github.com/kxepal/9da9f46ead6df8f1f198)

**Comment by kxepal** [comment]
Yes, mistakes are bad, but I think one traceback in stderr is enough to understand what went wrong and how to fix that (:

**Comment by DRMacIver** [comment]
Oh yes, I see what's going on. You'd actually get this in most strategies with an error in a user defined function. It's the initial health check downgrading an exception in reify into a warning.

Should be straightforward enough to fix so you just get the initial healthcheck followed by the subsequent test failure.
