### ISSUE TITLE
Flatmap is inconvenient

### ISSUE THREAD

**Issue by matthiasgoergens** [DRMacIver/hypothesis#255]
Generators that chain flatmap are rather inconvenient to write.

**Comment by matthiasgoergens** [comment]
Please see https://github.com/DRMacIver/hypothesis/pull/254 for a suggestion on how to present users of the library with a less cumbersome syntax.

**Comment by DRMacIver** [comment]
Have you seen the [composite decorator](http://hypothesis.readthedocs.org/en/latest/data.html#composite-strategies)? I think it's what you want.

**Comment by DRMacIver** [comment]
Given the existing solution to this problem, I'm going to close this ticket.
