### ISSUE TITLE
Health check for slow strategies should give more info

### ISSUE THREAD

**Issue by Daenyth** [DRMacIver/hypothesis#262]
Ideally, the specific generator which is slow. Failing that, at least which test method is calling slow generators. `@given` should have access to that information.

Maybe even linking to a guide on how to profile generators, gotchas, etc, so it's actionable

**Comment by DRMacIver** [comment]
I agree and I'm interested in doing this, but it's *really* hard to figure out this information. I don't currently have any good ideas.

RE profiling: It's definitely more of an art than a science right now. I wrote http://www.drmaciver.com/2015/07/notes-on-hypothesis-performance-tuning/ a while ago which needs to be updated and turned into documentation.

**Comment by Daenyth** [comment]
Is there any low-hanging fruit that could do this? For example, could `@given` do anything to at least isolate the line of the first invocation that triggers the slow warning?

**Comment by DRMacIver** [comment]
I suppose it would be possible to expose the strategy tree structure and do some example minimization on that tree to get a minimal slow strategy, but right now all that's happening with the slowness detection is seeing if you can generate 10 examples from the strategy in < a second.

**Comment by Daenyth** [comment]
I think you might have the context to print `test.__name__` at the [health check](https://github.com/DRMacIver/hypothesis/blob/master/src/hypothesis/core.py#L633), no?

If I have some time I'll try to put together a PR that at least does that; even with that minimal information I could start tracking down my cases.

It might help to also include a metric of attempted examples vs filtered examples; I think that's likely to be the biggest cause of slow generators.

**Comment by DRMacIver** [comment]
Oh, right I see. Sorry, I had misunderstood the difficulty. You're running with a test framework which doesn't capture output within tests, so that's not obvious. Are you using unittest? You might be better off turning output capturing on.

**Comment by DRMacIver** [comment]
(I couldn't remember how to do that, so if you can't either: It's the -b command line argument: https://docs.python.org/2/library/unittest.html#command-line-options )

**Comment by Daenyth** [comment]
I'm using nose; it only prints output on test failures, but the output I get from hypothesis doesn't come associated with the test name, but rather is printed before all the failure outputs are printed.

**Comment by DRMacIver** [comment]
Hmm. That's surprising. It's a warning emitted when you run the test.

**Comment by Daenyth** [comment]
Is it on stderr? I think nose only collates stdout.

**Comment by DRMacIver** [comment]
It is on stderr, yes. Not capturing that seems like a rather poor decision on nose's part TBH. I'm happy to accept a pull request to add the test name to the message if you want to, but I do think the real problem is nose not letting you isolate which test is emitting a warning.

In general it's seeming like warnings do not interact at all well with any of the python testing frameworks, so the health check failures are probably going to turn into errors in a later version. In the mean time if you want to make it easier to debug the easiest thing to do is probably to set the environment variable HYPOTHESIS_STRICT_MODE=true or put it in your settings.

**Comment by DRMacIver** [comment]
As of 3.0 the health checks are errors rather than warnings, so this should no longer be a problem.
