### ISSUE TITLE
Hypothesis shrinks to the minimalest example as possible since 1.18

### ISSUE THREAD

**Issue by kxepal** [DRMacIver/hypothesis#265]
It's all started from the morpher changes at 4ac882867634af3b637330b431db8e9b36f4199b. Assume we need to generate dictionaries with the specific optional fields. The basic strategy to do this would be:
```
from hypothesis import strategies as st
from hypothesis import find

def dict_with_optional_fields(**optional_fields):
    @st.composite
    def generator(draw, optional_fields=optional_fields):
        keys = draw(st.sets(elements=st.sampled_from(optional_fields)))
        return draw(st.fixed_dictionaries({key: optional_fields[key] for key in keys}))
    return generator

assert find(dict_with_optional_fields(test=st.none()), lambda _: True) == {}
```

In hypothesis releases before 1.18 that assertion was always True. Since 1.18 and morpher changes it became flaky: it may be true, or it may be false due to `{'test': None}` as the minimal example that is located. 

One of the workarounds is to use composite strategy, but it actually still flaky, just with a bit higher probability to not hit the issue. The other workaround is to raise max_examples limit up to 10K (at least). Note, that `hypothesis.internal.debug.minimal` which uses 5000 examples limit still on the edge of right and wrong result for example strategy.

The best workaround is to explicitly check for the condition you expect e.g. if minimal example for our strategy shouldn't contains `test` field, you need to use `lambda v: 'test' not in v` instead of just `lambda _: True`. Explicit things are better for sure, but this will raises overall test execution time.

**Comment by DRMacIver** [comment]
This should now be fixed in 3.0.

**Comment by kxepal** [comment]
The example is broken in 3.0:
```
hypothesis.errors.InvalidArgument: Expected SearchStrategy but got <function accept.<locals>.d at 0x7f44b29cd158> of type function
```
because `@st.composite` now creates not a SearchStrategy, but something else. Is that expected?

**Comment by DRMacIver** [comment]
I think this example must always have been broken. Was there a transcription error? composite has never returned a strategy object - it's always defined a function that returns a strategy object. The correct way to write this is:

```python
@st.composite
def dict_with_optional_fields(draw, **optional_fields):
    keys = draw(st.sets(elements=st.sampled_from(optional_fields)))
    return draw(st.fixed_dictionaries({key: optional_fields[key] for key in keys}))
```

**Comment by kxepal** [comment]
Oh, it was possible to do like that? But I figured my fault: instead of just `return generator` need to `return generator()` to unfold internal decorator into SearchStrategy.

And yes, it seems to works now!
