### ISSUE TITLE
Proposal: expose hypothesis.internal.debug.minimal helper for public API

### ISSUE THREAD

**Issue by kxepal** [DRMacIver/hypothesis#266]
During own strategies testing, the `find(st, lambda _: True)` is quite common patterns to find the minimal value produced by a strategy. I think that exposing `minimal` function would make things semantically more better and reduce learning curve angle for new users about what `lambda _: True` means.

If you're ok with, I can make a patch for this. This will also require to ease the way how `minimal` override settings values: I think user explicitly provided own ones, there is no need to do anything with them.

**Comment by DRMacIver** [comment]
Could you give me an example use case? It's mostly a legacy internal testing API (it predates the existence of find!). There's a decent chance I'll get around to removing it entirely at some point.

In general I'd rather not expand the public API with convenience functions unless there's a really compelling reason to.

**Comment by kxepal** [comment]
Well, one is in https://github.com/DRMacIver/hypothesis/issues/265
Another is for ip addresses:
```
def test_ipv4_minimal():
    assert '0.0.0.0' == hypothesis.find(ipv4(), lambda _: True)
    assert '0.0.0.0' == hypothesis.minimal(ipv4())  # looks and reads better, right?
```

Any tests that involves checking the minimal possible example would be fine. 

I agree that it's actually a wrapper over `find` call and brings nothing new, but repeating `lambda _: True` all the time forces for testing own strategies forces to implement own `minimal` wrapper as well. And since hypothesis already uses similar for own tests, sharing the same tools for testing strategies will cause only good.

**Comment by DRMacIver** [comment]
I'm completely OK with people reimplementing minimal() if they find they need it.

For the use case of testing strategies, I've got some ideas for updating the hypothesis.strategytests and making it official API.

In general, the cost of committing to "trivial" features in the public interface is much higher than the cost of people who need them writing the relevant smallq uantity of code.

**Comment by kxepal** [comment]
Makes sense. Something like `hypothesis.strategytests` would be nice to have. Closing then. Thanks for feedback!
