### ISSUE TITLE
Good way to time out a non-responsive test and consider it failed?

### ISSUE THREAD

**Issue by fasaxc** [DRMacIver/hypothesis#272]
I was testing a parser based on pyparsing using the `text()` strategy.  Unfortunately, the failure mode on bad input for my parser seems to be some sort of infinite loop.  Is there a good way to time out a test and consider that a failure to be reduced?  I'm using nose, in case that helps.

**Comment by DRMacIver** [comment]
There isn't really unfortunately. This is quite hard to do well. You could use this [internal debug function](https://github.com/DRMacIver/hypothesis/blob/master/src/hypothesis/internal/debug.py#L40) I have if you like, but obviously it's not stable public API or particularly good.

In general I think this is beyond the scope of what Hypothesis is for and there should be some other library providing a decorator for this. Unfortunately it's kinda a hard thing to do well and I'm not aware of whether any of the options are any good.
