### ISSUE TITLE
Automatic code Python

### ISSUE THREAD

**Issue by arita291** [DRMacIver/hypothesis#276]
Hi,
I discovered your package by StackOverFlow:
http://stackoverflow.com/questions/35492553/automatically-generate-data-for-unit-testing-in-python/35498029#35498029

My idea is having a python module,
can a program "analyze" at some extent
What the functions are "doing" ?
by using inspect package, and meta class and limited to numerical data (string data can be too complex).

WITHOUT any user input, only generic meta parametrization of Python type (array, int, float,....array2D,....)

ie: 
1) Get the list of errors.
2) Get data where result exists
3) computation time

I think your package is close this question.

What do you think of ?

It seems one still need to define invariants of the function...

**Comment by The-Compiler** [comment]
I think you're looking for static analysis and a linter, something like [pylint](https://pylint.org/)/[astroid](https://astroid.org/) or [jedi](http://jedi.jedidjah.ch/en/latest/). I don't think what you're describing is related to hypothesis.

**Comment by arita291** [comment]
I don't think so.
Runtime analysis is necessary to see the boundaries of the input (ex: positive value for square root..., array size...) and output.

Static analysis is needed only to parametrize correctly the inputs.


It seems Hypothesis is using in loop the invariant by throwing a set of semi parametrized "random" data.

Is it correct ?

**Comment by arita291** [comment]
To add:
In Hypothesis, 
By choosing the invariant instead of the data, we need to understand first exactly what the function is doing (input and output) and logical structure.

2nd question, can we use the Hypothesis Data generator code without using the invariant 

2) Suppose we have multi-dimensionnal array, does Hypothesis can generate the data ?

Project looks interesting.

**Comment by DRMacIver** [comment]
No, this isn't really what Hypothesis is for. It would be a much harder problem, and it's not one I'm very interested in trying to tackle.

**Comment by arita291** [comment]
Hi,

Your answer"No",
was on which question ?

Data Generator Class without invariant hypothesis ?

Or

Multidimensionnal array ?
