### ISSUE TITLE
FailedHealthCheck not a warning anymore

### ISSUE THREAD

**Issue by kitchoi** [DRMacIver/hypothesis#282]
Thanks for doing the great work in improving the package.

I am wondering what is the rationale of changing the FailedHealthCheck to an error instead of a warning.  Isn't it a bit too strict?

For example, a number of my tests require samples that do take some time to generate and there is no way around it except for drawing smaller samples and making the tests less robust.  I want to go for robustness than speed.  May I suggest a revert on that decision?

**Comment by DRMacIver** [comment]
So the problem with making it a warning is that warnings are basically useless in the Python testing ecosystem - nose or unit.test don't attach them to the tests and py.test will swalow them if the test passes.

The point of making them an error isn't to make them mandatory, but to make them unmissable when they happen. If your tests are failing the health checks and you think this is legit, you can disable the health checks on a per test basis with settings(perform_health_check=False). Is there a reason you don't want to do that?

**Comment by Daenyth** [comment]
What if we want to disable the "slow generation" warning but not the other ones? Maybe a `@settings(disable_health_checks=["slow_generation"])`

**Comment by kitchoi** [comment]
Thanks @DRMacIve.  That makes sense.
Thanks for pointing me to the `settings`, I didn't know about that (my bad. it is on the docs).  And I agree with @Daenyth that it would be better to be able to fine tune which health checks I want to skip.  For my use case, it would still be nice if the test warns/errors for too much filtering and recursive branching.

**Comment by DRMacIver** [comment]
I agree more fine grained filtering of health checks is a useful feature that should be implemented at some point, but they will definitely remain errors so I'm going to close this.
