### ISSUE TITLE
[Suggestion] Protocol for pretty-printing falsifying examples

### ISSUE THREAD

**Issue by Daenyth** [DRMacIver/hypothesis#310]
I'd like to add support for a `__pretty_str__` (or similar) protocol that hypothesis can use when printing falsifying examples. I have some generated data where my inputs can get quite large and complex, and usually I have to copy/paste into vim and manually format the results. The pretty printing wouldn't be appropriate for `__str__` or `__repr__` because those often show up in logger statements and can be shortened, whereas for the test failure I'd like to see more detailed/formatted results.

Would a PR adding this behavior be accepted? If not, is there any plugin system or protocol I can tap into (with a pytest plugin?) which could be used to maintain the behavior in a modular way? I'd much rather do that than try to maintain a fork if this isn't a change you feel is appropriate for the main project.

**Comment by DRMacIver** [comment]
Hypothesis actually *does* support the pretty_str protocol as of 3.1, but you're forgiven for not realising this as I haven't documented it anywhere.

**Comment by Daenyth** [comment]
What's the exact method name I should implement? Returning bytes or unicode?

**Comment by DRMacIver** [comment]
Ah, sorry, that's what I get for not actually looking. The method is called __repr_pretty_ and it follows (indeed, is a vendored and slightly patched version that I still need to upstream some stuff from) [the pretty printing protocol that IPython uses](https://ipython.org/ipython-doc/3/api/generated/IPython.lib.pretty.html).

**Comment by Daenyth** [comment]
Thanks!
