### ISSUE TITLE
A test fails by raising TypeError exception whenever one of the test function arguments is named 'f'

### ISSUE THREAD

**Issue by ramunas** [DRMacIver/hypothesis#38]
A test will always fail with the exception that an instance of HypothesisProvided is not callable whenver
one of the arguments test function arguments is named 'f'. For example, given

    @given(int, int)
    def test_this(x,f):
        assume(x > 1)
        assert x > 1

when run with py.test produces

    _________________________________________________________________ test_this __________________________________________________________________

    x = HypothesisProvided(value=<class 'int'>), f = HypothesisProvided(value=<class 'int'>)

        def test_this(x=not_set, f=not_set):
    >       return f(x=x, f=f)
    E       TypeError: 'HypothesisProvided' object is not callable

    .hypothesis/eval_source/hypothesis_temporary_module_06cffbd9c8baa4dbbfa21a56fbd77c45e3b770be_0.py:5: TypeError

however, the following

    @given(int, int)
    def test_this(x,y):
        assume(x > 1)
        assert x > 1

works just fine. Note that I renamed 'f' to 'y'. I get the same outcome regardless of the number of arguments a test function has.

If it help, I'm on `platform darwin -- Python 3.4.3 -- py-1.4.26 -- pytest-2.6.4` according to py.test.

**Comment by DRMacIver** [comment]
Ha. What a weird bug. You're entirely right, and I'm pretty sure I know how this is happening. I'll try to have a fix out soon.

**Comment by DRMacIver** [comment]
Right. This should be fixed now. If you upgrade to 0.7.2 everything should work.

**Comment by DRMacIver** [comment]
Oh, I meant to say by the way, thanks for the well put together bug report.
