### ISSUE TITLE
Documentation: Descriptors don't exist anymore

### ISSUE THREAD

**Issue by hedmundson** [DRMacIver/hypothesis#40]
In the docs:

This code  on page    doesn't work anymore:
>>> import hypothesis.descriptors as desc

>>> strategy([desc.integers_in_range(1, 10)]).example()
[7, 9, 9, 10, 10, 4, 10, 9, 9, 7, 4, 7, 7, 4, 7]

In[10]: strategy([desc.floats_in_range(0, 1)]).example()
[0.4679222775246174, 0.021441634094071356, 0.08639605748268818]

>>> strategy(desc.one_of((float, bool))).example()
3.6797748715455153e-281

>>> strategy(desc.one_of((float, bool))).example()
False

It appears hypothesis.descriptors is now hypothesis.specifiers

I know this is a minor change, but I'm in the process of reading the docs myself, so I don't trust myself to get everything exactly correct!

**Comment by DRMacIver** [comment]
Oops. Good catch, thanks. I thought I'd fixed all of those but evidently not.
