### ISSUE TITLE
Issue: specifiers.floats_in_range() returns floats not in range

### ISSUE THREAD

**Issue by hedmundson** [DRMacIver/hypothesis#41]
for i in range(1, 20):
    print strategy(spec.floats_in_range(.5,1)).example()

RETURNS:
0.968588265907
0.569918309757
0.806252086243
0.182544019517 *****
0.98129418528
0.964912189405
0.707089910335
0.201839450826 *******
0.510918699796

Things get worse for smaller ranges:
for i in range(1, 20):
    print strategy(spec.floats_in_range(.5,.51)).example()

RETURNS:

0.214248244349
0.601758048096
0.420202881225
0.545288818055
0.523624722385
0.70708993713
0.446426877632
0.570118640575
0.510503224163
0.529512864265
0.733973471751
0.518818519475
0.487080865111
0.54701095173
0.592756742708
0.36979839466
0.743264942082
0.499588510816
0.2745099114

All of these values fall out of the range given.

**Comment by DRMacIver** [comment]
Ack. That is indeed a big issue. I'll get right on it. Thanks.

(And I now owe you a beverage of your choice should we find ourselves in
the same city, as per the bug bounty promise)

**Comment by DRMacIver** [comment]
In general by the way I'd prefer bug reports via github issues (
https://github.com/DRMacIver/hypothesis/issues)  This is fine too, but it's
just easier to keep track of things that way.

**Comment by DRMacIver** [comment]
(Sorry if you saw an incoherent message about github issues. If you did ignore that, I was being stupid).

This should now be fixed. I've shipped a 0.9.2 release with a patch for this issue in it.

**Comment by hedmundson** [comment]
Thanks for fixing! Like the tests!
