### ISSUE TITLE
Why is pytest pinned to 2.6?

### ISSUE THREAD

**Issue by Ayrx** [DRMacIver/hypothesis#43]
Ref: https://github.com/DRMacIver/hypothesis/blob/master/hypothesis-extra/hypothesis-pytest/setup.py#L52

Now that pytest 2.7 is out things break.

**Comment by DRMacIver** [comment]
Things don't break, they work exactly as intended in that they stop you using version combinations that haven't been tested. :-)

But you're right that I should have tested hypothesis-pytest with the new 2.7.0 release. Too many things in the air at once and I forgot to check. It works fine, so I've released a new patch release which declares it compatible with pytest 2.7.x.

**Comment by Ayrx** [comment]
Cheers. :)
