### ISSUE TITLE
numpy support

### ISSUE THREAD

**Issue by LucidOne** [DRMacIver/hypothesis#50]
It seems reasonable to add support for numpy data types.

**Comment by DRMacIver** [comment]
I agree entirely. It's on the rather long TODO list.

In the meantime you can probably do a decent job using the built-in types and map, but I agree full support would be nicer.

**Comment by DRMacIver** [comment]
Now with extremely basic numpy support: https://pypi.python.org/pypi/hypothesis-numpy
