### ISSUE TITLE
Tracker accepts, but not support iterables

### ISSUE THREAD

**Issue by kxepal** [DRMacIver/hypothesis#55]
```python
from hypothesis.internal.tracker import Tracker

def test_track_iterable():
    t = Tracker()
    assert t.track(iter([1])) == 1
    assert t.track(iter([1])) == 2
```

Causes

```
  File "/home/kxepal/projects/sandbox/sandbox/testbox.py", line 23, in test_track_iterable
    assert t.track(iter([1])) == 1
  File "/usr/local/opt/virtualenv/sandbox/lib/python3.3/site-packages/hypothesis/internal/tracker.py", line 64, in track
    k = object_to_tracking_key(x)
  File "/usr/local/opt/virtualenv/sandbox/lib/python3.3/site-packages/hypothesis/internal/tracker.py", line 47, in object_to_tracking_key
    k = marshal.dumps(flatten(o))
  File "/usr/local/opt/virtualenv/sandbox/lib/python3.3/site-packages/hypothesis/internal/tracker.py", line 39, in flatten
    result.append(len(t))
TypeError: object of type 'list_iterator' has no len()
```

This happens because the iterator passed to the [branch](https://github.com/DRMacIver/hypothesis/blob/master/src/hypothesis/internal/tracker.py#L37-L40) which accepts [Iterable](https://docs.python.org/3.4/library/collections.abc.html#collections.abc.Iterable) instances. However, these instances are guarantee to implements `__next__`, but not `__len__` which have [Sized](https://docs.python.org/3.4/library/collections.abc.html#collections.abc.Sized) ones. May be you expected here [Sequence](https://docs.python.org/3.4/library/collections.abc.html#collections-abstract-base-classes) instances which are implements both `Sized` and `Iterable` interfaces to pass `len(...)` and `list(...)` calls?

**Comment by DRMacIver** [comment]
Good point. This actually doesn't cause a problem because Tracker is expected to handle only quite a restricted set of types, all of which implement either both or neither of iterable or len, but it's a still a bit rubbish. I'll fix it.
