### ISSUE TITLE
support nice syntax for sharing failing cases

### ISSUE THREAD

**Issue by graingert** [DRMacIver/hypothesis#57]
I've written some code and tested it with `hypothesis` but I'd like to store the failing tests and share them with other developers working on my project

I'm currently doing:

```python
def assert_like_foo(x, y):
    assert bar(ham(x), ham(y)) == foo(x, y)

@pytest.mark.parametrize("x,y",[
    (0.5, 0.3),
    (1e-310, 1e-300),
    (1e-300, 1e-310),
    (float('inf'), float('inf')),
    (4.0, 1.677633824243504e-308),
    (3.9999999999999996, 2.2250738585072014e-308),
])
def test_bar_parametrized(x, y):
    assert_like_foo(x, y)


@hypothesis.given(x=float, y=float)
def test_bar(x, y):
    assert_like_foo(x, y)
```

This seems a bit long winded, I'd like to do something more like:

```python
@hypothesis.given(x=float, y=float, _eg=[
    (0.5, 0.3),
    (1e-310, 1e-300),
    (1e-300, 1e-310),
    (float('inf'), float('inf')),
    (4.0, 1.677633824243504e-308),
    (3.9999999999999996, 2.2250738585072014e-308),
])
def test_bar(x, y):
    assert bar(ham(x), ham(y)) == foo(x, y)
```

**Comment by DRMacIver** [comment]
Yeah, it's becoming increasingly clear that something like this is needed. The test DB is a nice feature for local development but until there's a good workflow for sharing one (and probably even then) it should be possible to do it in the source code manually.

I'll see what I can do.

**Comment by DRMacIver** [comment]
Now supported with the example decorator in 1.2
