### ISSUE TITLE
source_exec_as_module() produces ResourceWarning

### ISSUE THREAD

**Issue by martinth** [DRMacIver/hypothesis#66]
When running test on Python 3.4 I get the following warnings on the console:

```
[...]site-packages/hypothesis/internal/reflection.py:316: ResourceWarning: unclosed file <_io.TextIOWrapper name='[...]/.hypothesis/eval_source/hypothesis_temporary_module_ae7c3d261715e28e9832a153df34d35ccc6c70ff.py' mode='r' encoding='UTF-8'>
  assert open(filepath).read() == source
```

This is caused by [this](https://github.com/DRMacIver/hypothesis/blob/master/src/hypothesis/internal/reflection.py#L316) assertion. The easiest (but less good looking) way would probably by to replacethis with:

```python
with open(filepath) as f:
    assert f.read() == source
```

**Comment by DRMacIver** [comment]
Oops. Good catch. Thanks.

**Comment by martinth** [comment]
Goddamit, you are scary fast on this! Big thx for your work :+1:

**Comment by DRMacIver** [comment]
Weirdly, I can't actually reproduce the warning. I've tried to upgrade ResourceWarning to an error in my tests, but this doesn't fail even with the old slightly leaky code.

The code in question is obviously wrong, so I've fixed it anyway, but I'm a little puzzled as to what's going on here.

**Comment by DRMacIver** [comment]
Oh! I see. ResourceWarning only happens if Python was built in debug mode.

I suppose I should add a debug mode Python to my CI. I forgot that was a thing.

**Comment by martinth** [comment]
I'm running a Vagrant container with a standard Ubuntu 14.04 inside and execute my tests with nose. Does that mean, that Ubuntu ships a debug build by default?

**Comment by DRMacIver** [comment]
I guess it must be. That's a bit weird if so! But [the docs say](https://docs.python.org/3.2/library/warnings.html#default-warning-filters) it's ignored outside of debug mode.

**Comment by DRMacIver** [comment]
(I don't use the system default installs because I have to deal with too many different python versions)

**Comment by DRMacIver** [comment]
Oh, it could also be that something you're using is just changing the warning filters.
