### ISSUE TITLE
Docs example fails

### ISSUE THREAD

**Issue by Echocage** [DRMacIver/hypothesis#67]
The decorator given([int]) is creating tests with empty lists, which is breaking this test example from the documentation

```python
@given([int])
def test_reversing_twice_gives_same_list(xs):
    assert xs == list(reversed(reversed(xs)))
```
Apparently a reversed empty list isn't a squence, which might be an issue in it of it self

**Comment by DRMacIver** [comment]
Oops! The empty lists are deliberate, and not actually the source of the problem (you just can't apply reversed(reversed(x)) in python. Silly me), but it certainly wasn't deliberate that the example was wrong. Thanks for the catch.
