### ISSUE TITLE
Map and flatmap fail on functions without names

### ISSUE THREAD

**Issue by saulshanabrook** [DRMacIver/hypothesis#68]
Not all functions have the `__name__` attribute, but `map` and `flatmap` will crash if the function does not.

For example, if you wrap a function with `itertools.partial` the result will not have a `__name__` and so cannot be used in `map`.

```
$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from hypothesis import given, assume, strategy
>>> func = lambda a, b: a+b
>>> import functools
>>> func_wrapped = functools.partial(func, 10)
>>> func_wrapped(1)
11
>>> func_wrapped(10)
20
>>> strategy(int).map(func_wrapped)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/hypothesis/searchstrategy/strategies.py", line 533, in __repr__
    self.mapped_strategy, self.pack.__name__
AttributeError: 'functools.partial' object has no attribute '__name__'
```

**Comment by DRMacIver** [comment]
Huh. I had no idea. Thanks for the report. Will fix.

**Comment by DRMacIver** [comment]
This is fixed in master. Should be in a release tomorrow or Tuesday.

**Comment by saulshanabrook** [comment]
@DRMacIver Wow you are amazing! Thank you so much!

**Comment by DRMacIver** [comment]
Heh. Not that amazing. Apparently I was wrong about it being fixed in master because I forgot to merge the branch. But it will be fixed in master today and will be in the next release.
