### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by skorokithakis** [DRMacIver/hypothesis#70]
I'm not sure whether it's the documentation or just me, but I can't, for the life of me, figure out how to use strategy. I can't see how to pass it to `@given`, and thus I'm not sure how to create a strategy that will give me examples of a list of given length.

I see the example that uses `flatmap` to do it, but how do I pass that strategy to `@given`? Is it mentioned anywhere that I have overlooked?

**Comment by DRMacIver** [comment]
I'll try to make this more obvious in the documentation, but the answer is that you pass a strategy to given like you would anything else: Arguments to given are just things that are convertible to strategies, and in particular they can themselves be strategies.

**Comment by skorokithakis** [comment]
Ah, thanks, I didn't see that anywhere, and didn't know whether there's a specific parameter that they need to be passed under. It's not immediately obvious that types can be converted to strategies.

**Comment by DRMacIver** [comment]
This should now be clear in the documentation as of 1.5 because everything takes a search strategy and the whole notion of things that are convertible to strategies is deprecated.
