### ISSUE TITLE
sampled_from is not a part of public API

### ISSUE THREAD

**Issue by Mishail** [DRMacIver/hypothesis#76]
``sampled_from`` is not in ``strategies.__all__`` so it's not imported by ``from hypothesis.strategies import *``
See https://github.com/DRMacIver/hypothesis/commit/4a371de39bd18405cfcf540b9f991666371317e5#diff-3d4bf7325812ead3078c4ebbb189343cR25

**Comment by DRMacIver** [comment]
Oops. You're right. Thanks for the report.

However I'd strongly discourage thinking of the public API as what you get when you import *. this is not what defines the public API.

**Comment by DRMacIver** [comment]
Fixed in the 1.6.2 release.
