### ISSUE TITLE
The required fakefactory version is too old and conflicts.

### ISSUE THREAD

**Issue by skorokithakis** [DRMacIver/hypothesis#79]
I'm using factory-boy and want to use hypothesis as well, but hypothesis uses an old fakefactory version and conflicts with factoryboy. Could we change the requirement to >=0.4.2?

**Comment by DRMacIver** [comment]
No, we can't. fake-factory is not API stable between minor versions and the same code does not work on both 0.4.x and 0.5.x. Additionally, 0.5.0 is basically a broken release as far as I'm concerned and won't be supported.

I'm pretty sure 0.5.1 fixes the problems with 0.5.0 though, and it's been on my TODO list to release a version compatible with it. I'll try to do so in the next few days.

**Comment by DRMacIver** [comment]
(0.5.1 hasn't been out for very long, and I've been busy since its release, which is why this isn't already done)

**Comment by skorokithakis** [comment]
Hmm, I'm using 0.5.2 right now without any problems, but I'm not really taxing it significantly. Are there any workarounds, perhaps?

**Comment by DRMacIver** [comment]
Oh I hadn't even noticed they'd also released a 0.5.2. That will definitely be supported too! The plan is to do a release with a new release of hypothesis-fakefactory with a dependency requirement of >= 0.5.1 < 0.5.99. It's only the 0.5.0 release that had problems.

What do you mean you're using it without any problems? With Hypothesis or on its own?

**Comment by skorokithakis** [comment]
Sorry, on its own (well, with factory boy). I want to use hypothesis for unit tests and factory boy for integration tests, so it'd be good if I could have both working together.

**Comment by DRMacIver** [comment]
Yeah, I'll try to have a fix for you tomorrow. It depends how much breaks in the new version.

**Comment by DRMacIver** [comment]
Looks like it's easy. I've got what I think is a working update to hypothesis-{fakefactory,django}. I don't want to release and then go to sleep, so I'll release in the morning.

**Comment by skorokithakis** [comment]
Thank you for the quick response!

**Comment by DRMacIver** [comment]
OK I've shipped new versions of hypothesis-fakefactory and hypothesis-django that should be compatible with the latest fake factory. Let me know if you have any further problems.

**Comment by skorokithakis** [comment]
Thank you!

**Comment by Mishail** [comment]
https://github.com/DRMacIver/hypothesis/blob/master/hypothesis-extra/hypothesis-fakefactory/setup.py#L55 still requires ```"fake-factory==0.4.2"```, and fails with 
```
E   VersionConflict: (fake-factory 0.5.2 (/usr/local/lib/python2.7/site-packages), Requirement.parse('fake-factory==0.4.2'))
```

**Comment by DRMacIver** [comment]
Argh. Thanks for the catch. I *did* fix this but somehow undid the fix in the latest version release. On it.

**Comment by DRMacIver** [comment]
Now fixed. Sorry about that.
