### ISSUE TITLE
Would like to be able to specify a factory for StatefulTest

### ISSUE THREAD

**Issue by rboulton** [DRMacIver/hypothesis#8]
I'd like to be able to make a StatefulTest subclass which had some way to pass parameters to __init__, or some way to control what factory is used for making example cases.

**Comment by DRMacIver** [comment]
https://github.com/DRMacIver/hypothesis/commit/0ba52cde9c5fc155f8bb1cb7a1eee4ac9394a498 adds the ability for a stateful test __init__ to get passed generated argument. Between that and the ability to subclass stateful tests I think this requirement is pretty much satisfied. Feel free to reopen if you think it isn't.
