### ISSUE TITLE
Support for Python 2.6

### ISSUE THREAD

**Issue by Jeff-Meadows** [DRMacIver/hypothesis#81]
I've got some py2.6 code I'd love to use hypothesis for.

There is a py2.6 tox env, but it's not in use and the package clearly doesn't work with 2.6.

I plan to submit a PR with 2.6 support if you're willing to accept it.

**Comment by DRMacIver** [comment]
I'm kinda against this. Not to the point of rejecting it out of hand, but not supporting Python 2.6 is something of a deliberate choice on my part. I wrote a bit about it here: http://www.drmaciver.com/2015/05/if-you-want-python-2-6-support-pay-me/

I'll probably accept a PR with 2.6 support, but I'd caution against your putting a bunch of time into this if you haven't already got it working, as you're probably underestimating how much work it is (and if you *have* already got it working, good job. So far 3 people including me have investigated and decided it was more work than they could be bothered with).

Also, if you do get 2.6 support working I make no promises about keeping it in. I'll basically keep it in as long as it's easy to do, but supporting a wide range of Python versions is in the top 2 or 3 most annoying things about Python library development, and if 2.6 significantly adds to that burden it's probably going to get dropped at some point.

**Comment by DRMacIver** [comment]
Oh, incidentally, a thing you might want to consider doing is using execnet. This will let you write your tests in a modern Python but run the actual test code in 2.6.

**Comment by smontanaro** [comment]
> I wrote a bit about it here:
http://www.drmaciver.com/2015/05/if-you-want-python-2-6-support-pay-me/

I just glanced at that. Our company (about 200 employees) went from 2.4 to
2.7. Wasn't hard. I think updating our ancient Boost.Python version was
probably the hardest thing. I doubt going from 2.6 to 2.7 would be much
more difficult than installing the later Python and recompiling extension
modules. You'd not be using any 2.7 features, but everything would just
run. OTOH, as a maintainer of a package, you'd want to use
some/many/most/all of the features in 2.7, so supporting 2.6 would be more
difficult. I completely understand your decision not to support 2.6.

Skip Montanaro

**Comment by DRMacIver** [comment]
I'm going to close this for now as, like I said, I have no intention of supporting it myself. Patches are still welcome if you really want to, but I don't think it's a good idea.

**Comment by Jeff-Meadows** [comment]
I understand the sentiment. I maintain a few Python libraries, and I decided to draw the line at 2.6 instead of 2.7. FWIW, I would not consider adding 2.5 support to those libraries.

I guess hypothesis-django is very unlikely to work with 2.6, since Django 1.7 requires Python 2.7 or greater.

I do have tox passing with a py26 env (minus django), but I'll just vendor it in to my project and give it some test runs to see if it "really" works with 2.6. And since you don't really want to support it, I probably won't try to push upstream unless some other people are also interested.

Thanks!

**Comment by DRMacIver** [comment]
Sigh. Due to reasons I have changed my mind. Jeff, if you're still willing to make that pull request I would very much appreciate it. If not, can you point me to the code and I'll finish it off?

**Comment by Jeff-Meadows** [comment]
Sure. I'll verify the code state (since it's been a week since I've been looking at this), and then I'll submit the PR.

**Comment by DRMacIver** [comment]
Great. Thanks!

Could you submit it to be merged into the "upcoming" branch please? I have a slightly weird branching structure that I need to document, but basically master is released version + documentation fixes, upcoming is for the next minor version release.

**Comment by DRMacIver** [comment]
OK, I've cherry-picked your main commit and got things properly integrated (in the course of which I found a bug in Python 2.6. Oh well. It doesn't actually affect me). 2.6 will be supported in the upcoming release.

Thanks again, @Jeff-Meadows!
