### ISSUE TITLE
floats(min_value=0, max_value=1) never tests for 0

### ISSUE THREAD

**Issue by ianozsvald** [DRMacIver/hypothesis#91]
Here's an example of the logit function, we'd like to test in the open range `(0,1)` and it should fail with a divide by 0 at `p=0` and `NaN` at `p=1`:
```
import numpy as np
from hypothesis import given
from hypothesis.strategies import floats

def logit(p):
    return np.log((1/p)-1)

@given(floats())
def test_fails_correctly_at_0(p):
    res = logit(p)
    # note we'd like to test the following but we never get here as (correctly)
    # the Divide By Zero is caught first
    #assert not np.isnan(res)

@given(floats(min_value=0.0, max_value=1))
def test_never_fails_but_should_at_0_and_1(p):
    res = logit(p)
    assert not np.isnan(res)
```

If we don't specify a range for `floats()` then `0` is tested as a nasty value, this causes a Divide By Zero error (and we'd then expect to improve our `logit` function to handle the edge case). As such we don't get to the `nan` test in `test_fails_correctly_at_0`.

In the second test I limit the range to `(0,1)` but we never get a `0`, so that edge (nor `1`) are tested. This limit is necessary as the `logit` function is only valid in this range.

**Comment by DRMacIver** [comment]
Yep. This is a good point which I really should have sorted out by now. My only excuse is that floating point numbers are unbelievably hairy and other more critical things got in the way. Those are now fixed though so it's not a very good excuse. :-) Will have something in this vein shortly.

**Comment by ianozsvald** [comment]
For the benefit of others who might read this - I see now that I can also use `@example(0.0)` (`from hypothesis import example`) to force specific examples, even in the `@given` generator doesn't produce quite what I want, so that's a work-around and useful if one wants to test a few very specific examples.

**Comment by DRMacIver** [comment]
As of the 1.8.0 release (out earlier today) this is fixed.

**Comment by ianozsvald** [comment]
Will be a few days before I can test - cheers!
