### ISSUE TITLE
Bytes strategy

### ISSUE THREAD

**Issue by radix** [DRMacIver/hypothesis#92]
I may be missing something, but it doesn't seem there's any bytes strategy. I'd suggest `strategies.bytes()` should produce str on Python 2 and bytes on Python 3. I suppose an `alphabet` to restrict the range of bytes produced would also be valuable.

**Comment by radix** [comment]
first approximation:

```python
bytes = st.builds(chr, st.integers(min_value=0, max_value=255))
```

**Comment by DRMacIver** [comment]
I think you're looking for the "binary" strategy?

**Comment by radix** [comment]
Okay, the documentation of `binary` had a bug: I just created PR #94 to fix it to mention `bytes` (which would have helped me find it :)

IMO `binary` is a misnomer, but having the documentation corrected will at least help people find it.

**Comment by radix** [comment]
Oh, and thank you very much for Hypothesis and for your quick response :) I'll close this issue.
