### ISSUE TITLE
Generating nested dicts?

### ISSUE THREAD

**Issue by aldanor** [DRMacIver/hypothesis#93]
Wondering if it is possible to generate nested dicts (e.g. a tree where all leaves are of a certain type and the intermediate keys are of another type, maybe with some assumptions on the structure) with hypothesis? 

Defining such a strategy recursively using the primitives doesn't seem to work since it would require hypothesis to support forward declarations...

**Comment by DRMacIver** [comment]
Yeah, this needs better support. Currently recursive data like this is a real pain to do in Hypothesis. I've got some ideas germinating for how to make it better, but they're not there yet.

In the mean time, the best thing to do for this is probably to use the stateful testing support. You can basically define rules to build your data from smaller types (which can be recursive).

You can also use the under documented and slightly unofficial NAryTree strategy and map over that: https://github.com/DRMacIver/hypothesis/blob/master/src/hypothesis/searchstrategy/narytree.py

**Comment by aldanor** [comment]
Great, thanks, will take a look.

I was thinking maybe it could be implemented along the same lines as `Forward` expressions in `pyparsing`:

```python
>>> strategy = strategies.forward(maxdepth=5)
>>> leaf = strategies.integers() | strategies.text()
>>> strategy << leaf | strategies.lists(strategy)
```

**Comment by DRMacIver** [comment]
Hm. That's interesting. It might be possible to do. I'll have a think about it.

**Comment by DRMacIver** [comment]
This is now supported with [the new recursive feature](http://hypothesis.readthedocs.org/en/latest/data.html#recursive-data). It's not the model you suggested, but it'll achieve the requested example of nested dicts. You can do this as recursive(leaf_labels, lambda trees: dictionaries(key_labels, trees)).
