### ISSUE TITLE
Doc clarification for `strictly_simpler`

### ISSUE THREAD

**Issue by eentzel** [DRMacIver/hypothesis#97]
The [docstring](https://github.com/DRMacIver/hypothesis/blob/0e7feebdf5f2a26d0bfba7e11a464dcc2dcd81fe/src/hypothesis/searchstrategy/strategies.py#L329) for `strictly_simpler` says:

>        Required properties:
>        1. not strictly_simpler(x, y)

Either I'm missing something, or this should be `not strictly_simpler(x, x)`, no?

**Comment by DRMacIver** [comment]
Woops, sorry I dropped doing something about this. Not sure how that happened! Thanks for the catch.

**Comment by eentzel** [comment]
Thanks for all your great work on Hypothesis — thanks in particular for writing about it so extensively, I really enjoy your posts!
