### ISSUE TITLE
[feature request] Unicode that could catch-out MySQL's default unicode settings

### ISSUE THREAD

**Issue by ianozsvald** [DRMacIver/hypothesis#98]
I'm posting this as a feature-request given our chat at pydatalondon but it is cool if it is too specific to include in the standard library.

By default MySQL supports 3 byte Unicode encoding (`utf8`) rather than 4 bytes to do it properly, you have to explicitly choose `utf8mb4` (https://mathiasbynens.be/notes/mysql-utf8mb4) and you'll probably do that after you've suffered data loss. Python's unicode isn't to blame, it correctly sends out things like the pile-of-poo character (`"\N{PILE OF POO}"`) and MySQL's defaults don't encode it.

You _could_ provide a variant of the `text` generator that favours harder unicode examples (e.g. stuff in the 2010 https://en.wikipedia.org/wiki/Plane_%28Unicode%29#Supplementary_Multilingual_Plane) like the infamous pile of poo (http://www.fileformat.info/info/unicode/char/1f64b/index.htm). This could be useful for testing both storage engines and web services (due to encoding data for the web).

The current `text` generator will presumably sample some of these, but maybe forcing some of the harder examples to be included would help folk flush out more bugs?

Sidenote - if anyone wants to play with this and discovers that they don't have font support then there are some details here (e.g. for Ubuntu): https://en.wikipedia.org/wiki/Emoji#Usage

**Comment by DRMacIver** [comment]
I'd be very surprised if Hypothesis's default text doesn't catch this problem - it generates unicode from the whole spectrum of representable characters, more or less uniformly at random (about 10% of the time it deliberately picks a low code point, the rest of the time it's uniform). Have you tried it and found that it didn't?

**Comment by ianozsvald** [comment]
Righto - I just tried it and yes, I see that a variety of text is produced and I can for example restrict it to `string.ascii_letters`. It wasn't clear to me that it sampled from the whole (full-unicode) range, though there's nothing in the docs to suggest that it didn't so I'm probably just being ascii-biased! In case anyone follows, here's an easy way to see the result:
```
from hypothesis.strategies import text, streaming
from hypothesis import strategy

t = strategy(streaming(text())).example()
# or use text(alphabet=string.ascii_letters) for just ascii
for n in range(100):
    print(t[n])
```

**Comment by DRMacIver** [comment]
FWIW if you want to see if Hypothesis can generate something you can also try things like the following:
```
>>> from hypothesis import find
>>> from hypothesis.strategies import text
>>> find(text(), lambda x: any(c >= "\U0001F4A9" for c in x))
'💩' 
```
